define({
	noBorder:'noBorder',
	noLeftBorder:'noLeftBorder',
	noRightBorder:'noRightBorder',
	noTopBorder:'noTopBorder',
	noBottomBorder:'noBottomBorder',
	left:'left',
	right:'right',
	clearRight:'clearRight',
	clearLeft:'clearLeft',
	clear:'clear',
	/*position*/
	positionS:'positionS',
	positionA:'positionA',
	positionR:'positionR',
	positionFix:'positionFix',
	show:'show',
	displayBlock:'displayBlock',
	displayInline:'displayInline',
	displayInlineBlock:'displayInlineBlock',
	displayInlineTable:'displayInlineTable',
	hide:'hide',
	overflowHide:'overflowHide',
	overflowAuto:'overflowAuto',
	overflowScroll:'overflowScroll',
	overflowVisible:'overflowVisible',
	visible:'visible',
	visibleFalse:'visibleFalse',
	listStyleNo:'',
	/* useful objects*/
	imageAds:'imageAds',
	triangle:'triangle',
	triangleTopGrey:'triangleTopGrey',
	triangleLeftGrey:'triangleLeftGrey',
	triangleRightGrey:'triangleRightGrey',
	triangleBottomGrey:'triangleBottomGrey',
	triangleTopWhite:'triangleTopWhite',
	triangleLeftWhite:'triangleLeftWhite',
	triangleRightWhite:'triangleRightWhite',
	triangleBottomWhite:'triangleBottomWhite',
	cursorPointer:'cursorPointer',
	font:{normal:'fontNormal',
		italic:'fontItalic',
		oblique:'fontOblique',
		smallcaps: 'fontVariant',
		weightNormal:'fontWeightNormal',
		'bold':'fontBord',
		bolder:"fontBorder",
		lighter:'fontLighter',
		xxsmall:'fontsizeXxsmall',
		xsmall:'fontsizeXsmall',
		'small':'fontsizeSmall',
		medium:'fontsizeMedium',
		large:'fontsizeLarge',
		xlarge:'fontsizeXlarge',
		xxlarge:'fontsizeXxlarge',
		'fontsize':'fontsize'
	},
	bg:{
		lightYellow:'bgLightYellow',
		lightRed:'bgLightRed',
		lightGreen:'bgLightGreen',
		lightBlue:'bgLightBlue',
		lightGrey:'bgLightGrey',
		lightGrey2:'bgLightGrey2',
		yellow:'bgYellow',
		red:'bgRed',
		green:'bgGreen',
		blue:'bgBlue',
		grey:'bgGrey',
		deepGrey:'bgDeepGrey',
		black:'bgBlack',
		white:'bgWhite'
	}, 
	bgHover:{
		lightYellow:'itemLightYellow',
		lightRed:'itemLightRed',
		lightGreen:'itemLightGreen',
		lightBlue:'itemLightBlue',
		lightGrey:'itemLightGrey',
		lightGrey2:'itemLightGrey2',
		yellow:'itemYellow',
		red:'itemRed',
		green:'itemGreen',
		blue:'itemBlue',
		grey:'itemGrey',
		deepGrey:'itemDeepGrey',
		black:'itemBlack',
		white:'itemWhite'
	},
	color:{
		lightYellow:'colorLightYellow',
		lightRed:'colorLightRed',
		lightGreen:'colorLightGreen',
		lightBlue:'colorLightBlue',
		lightGrey:'colorLightGrey',
		lightGrey2:'colorLightGrey2',
		yellow:'colorYellow',
		red:'colorRed',
		green:'colorGreen',
		blue:'colorBlue',
		grey:'colorGrey',
		deepGrey:'colorDeepGrey',
		black:'colorBlack',
		white:'colorWhite'
	},
	colorHover:{
		lightYellow:'itemColorLightYellow',
		lightRed:'itemColorLightRed',
		lightGreen:'itemColorLightGreen',
		lightBlue:'itemColorLightBlue',
		lightGrey:'itemColorLightGrey',
		lightGrey2:'itemColorLightGrey2',
		yellow:'itemColorYellow',
		red:'itemColorRed',
		green:'itemColorGreen',
		blue:'itemColorBlue',
		grey:'itemColorGrey',
		deepGrey:'itemColorDeepGrey',
		black:'itemColorBlack',
		white:'itemColorWhite'
	},
	text:{
		decNone:'textDecNone',
		decUnder:'textDecUnder',
		textDecOver:'textDecOver',
		textDecThough:'textDecThough',
		valignBase:'valignBase',
		valignSub:'valignSub',
		valignSuper:'valignSuper',
		valignTop:'valignTop',
		valignTtop:'valignTtop',
		valignMiddle:'valignMiddle',
		valignBottom:'valignBottom',
		valignTbottom:'valignTbottom',
		transCap:'tTransCap',
		transUpper:'tTransUpper',
		transLower:'tTransLower',
		alignL:'textAlignLeft',
		alignR:'textDecUnder',
		alignC:'textAlignCenter',
		textIndent:'textIndent',
		textIndentL:'textIndentL',
		'break':'wordWrapBreak',
		breakNormal:'wordBreakNormal',
		breakAll:'wordBreakAll',
		breakKeepAll:'wordBreakKeepAll',
		spaceNowrap:'wordSpaceNowrap',
		spacePre:'wordSpacePre',
		spacePreline:'wordSpacePreline',
		spacePrewrap:'wordSpacePrewrap'
	},
	box:{
		fullW:'fullWidth',
		fullH:'fullHeight',
		wAuto:'widthAuto',
		hAuto:'heightAuto',
		heightS:'heightS',
		heightM:'heightM',
		heightL:'heightL',
		heightLL:'heightLL',
		widthS:'widthS',
		widthM:'widthM',
		widthL:'widthL',
		widthLL:'widthLL',
		fullLineHeight:'fullLineHeight',
		lineHight:'lineHight',
		width:'width',
		height:'height',
		widthf:'width-fluid',
		heightf:'height-fluid',
		LRAuto:'marginLRAuto',
		noMargin:'noMargin',
		noLMargin:'noLeftMargin',
		noRMargin:'noRightMargin',
		noTopMargin:'noTopMargin',
		noBMargin:'noBottomMargin',
		'marginBottomNeg-1':'marginBottomNeg-1',
		noPadding:'noPadding',
		noLPadding:'noLeftPadding',
		noRPadding:'noRightPadding',
		noTopPadding:'noTopPadding',
		noBPadding:'noBottomPadding',
		marginTopSS:'marginTopSS',
		marginBSS:'marginBottomSS',
		marginRSS:'marginRightSS',
		marginLSS:'marginLeftSS',
		marginSS:'marginSS',
		paddingTopSS:'paddingTopSS',
		paddingBSS:'paddingBottomSS',
		paddingRSS:'paddingRightSS',
		paddingLSS:'paddingLeftSS',
		paddingSS:'paddingSS',
		marginTopS:'marginTopS',
		marginBS:'marginBottomS',
		marginRS:'marginRightS',
		marginLS:'marginLeftS',
		marginS:'marginS',
		paddingTopS:'paddingTopS',
		paddingBS:'paddingBottomS',
		paddingRS:'paddingRightS',
		paddingLS:'paddingLeftS',
		paddingS:'paddingS',
		marginTop:'marginTop',
		marginBottom:'marginBottom',
		marginRight:'marginRight',
		marginLeft:'marginLeft',
		margin:'margin',
		paddingTop:'paddingTop',
		paddingBottom:'paddingBottom',
		paddingRight:'paddingRight',
		paddingLeft:'paddingLeft',
		padding:'padding',
		marginTopL:'marginTopL',
		marginBottomL:'marginBottomL',
		marginRightL:'marginRightL',
		marginLeftL:'marginLeftL',
		marginL:'marginL',
		paddingTopL:'paddingTopL',
		paddingBottomL:'paddingBottomL',
		paddingRightL:'paddingRightL',
		paddingLeftL:'paddingLeftL',
		paddingL:'paddingL',
		marginTopLL:'marginTopLL',
		marginBottomLL:'marginBottomLL',
		marginRightLL:'marginRightLL',
		marginLeftLL:'marginLeftLL',
		marginLL:'marginLL',
		border:'border',
		borderLeft :'borderLeft',
		borderRight :'borderRight',
		borderTop :'borderTop',
		borderBottom :'borderBottom',
		
		borderM:'borderM',
		borderMLeft :'borderMLeft',
		borderMRight :'borderMRight',
		borderMTop :'borderMTop',
		borderMBottom :'borderMBottom',
		
		borderRed:'borderRed',
		borderRedLeft :'borderRedLeft',
		borderRedRight :'borderRedRight',
		borderRedTop :'borderRedTop',
		borderRedBottom :'borderRedBottom',
		
		borderLightYellow:'borderLightYellow',
		borderLightYellowLeft :'borderLightYellowLeft',
		borderLightYellowRight:'borderLightYellowRight',
		borderLightYellowTop :'borderLightYellowTop',
		borderLightYellowBottom :'borderLightYellowBottom',
		
		borderLightRed:'borderLightRed',
		borderLightRedLeft :'borderLightRedLeft',
		borderLightRedRight :'borderLightRedRight',
		borderLightRedTop :'borderLightRedTop',
		borderLightRedBottom :'borderLightRedBottom',
		
		borderLightGreen:'borderLightGreen',
		borderLightGreenLeft :'borderLightGreenLeft',
		borderLightGreenRight :'borderLightGreenRight',
		borderLightGreenTop :'borderLightGreenTop',
		borderLightGreenBottom :'borderLightGreenBottom',
		
		borderLightBlue:'borderLightBlue',
		borderLightBlueLeft :'borderLightBlueLeft',
		borderLightBlueRight :'borderLightBlueRight',
		borderLightBlueTop :'borderLightBlueTop',
		borderLightBlueBottom :'borderLightBlueBottom',
		
		borderLightGrey:'borderLightGrey',
		borderLightGreyLeft :'borderLightGreyLeft',
		borderLightGreyRight :'borderLightGreyRight',
		borderLightGreyTop :'borderLightGreyTop',
		borderLightGreyBottom :'borderLightGreyBottom',
		
		borderYellow:'borderYellow',
		borderYellowLeft :'borderYellowLeft',
		borderYellowRight :'borderYellowRight',
		borderYellowTop :'borderYellowTop',
		borderYellowBottom :'borderYellowBottom',
		
		borderRed:'borderRed',
		borderRedLeft :'borderRedLeft',
		borderRedRight :'borderRedRight',
		borderRedTop :'borderRedTop',
		borderRedBottom :'borderRedBottom',
		
		borderGreen:'borderGreen',
		borderGreenLeft :'borderGreenLeft',
		borderGreenRight :'borderGreenRight',
		borderGreenTop :'borderGreenTop',
		borderGreenBottom :'borderGreenBottom',
		
		borderBlue:'borderBlue',
		borderBlueLeft :'borderBlueLeft',
		borderBlueRight :'borderBlueRight',
		borderBlueTop :'borderBlueTop',
		borderBlueBottom:'borderBlueBottom',
		
		borderGrey:'borderGrey',
		borderGreyLeft :'borderGreyLeft',
		borderGreyRight :'borderGreyRight',
		borderGreyTop :'borderGreyTop',
		borderGreyBottom :'borderGreyBottom',
		
		borderBlack:'borderBlack',
		borderBlackLeft :'borderBlackLeft',
		borderBlackRight :'borderBlackRight',
		borderBlackTop :'borderBlackTop',
		borderBlackBottom :'borderBlackBottom',
		
		borderWhite:'borderWhite',
		borderWhiteLeft :'borderWhiteLeft',
		borderWhiteRight :'borderWhiteRight',
		borderWhiteTop :'borderWhiteTop',
		borderWhiteBottom :'borderWhiteBottom',
		
		borderGrey_1:'borderGrey_1',
		borderGrey_1_Left :'borderGrey_1_Left',
		borderGrey_1_Right :'borderGrey_1_Right',
		borderGrey_1_Top :'borderGrey_1_Top',
		borderGrey_1_Bottom :'borderGrey_1_Bottom',
		
		borderGrey_2:'borderGrey_2',
		borderGrey_2_Left :'borderGrey_2_Left',
		borderGrey_2_Right :'borderGrey_2_Right',
		borderGrey_2_Top :'borderGrey_2_Top',
		borderGrey_2_Bottom :'borderGrey_2_Bottom',
		
		borderGrey_3:'borderGrey_3',
		borderGrey_3_Left:'borderGrey_3_Left',
		borderGrey_3_Right :'borderGrey_3_Right',
		borderGrey_3_Top :'borderGrey_3_Top',
		borderGrey_3_Bottom :'borderGrey_3_Bottom',
		
		borderGrey_4:'borderGrey_4',
		borderGrey_4_Left:'borderGrey_4_Left',
		borderGrey_4_Right :'borderGrey_4_Right',
		borderGrey_4_Top :'borderGrey_4_Top',
		borderGrey_4_Bottom :'borderGrey_4_Bottom'
	}
});